This is a testharness.js-based test.
Harness Error. harness_status.status = 1 , harness_status.message = 10 duplicate test names: "This tests Get function", "This tests case sensitive scenario", "Tests Undefined", "Tests matchesNothingInDataset", "Tests Set", "Tests Is Null", "Tests Delete", "Tests Native Delete", "Tests For In", "Set null"
PASS This tests Get function 
PASS This tests case sensitive scenario 
PASS Tests Undefined 
PASS Tests matchesNothingInDataset 
FAIL Tests Set Test bug: need to pass exception to assert_throws()
PASS Tests Is Null 
PASS Tests Delete 
PASS Tests Native Delete 
PASS Tests For In 
PASS Set null 
PASS This tests Get function 
PASS This tests case sensitive scenario 
PASS Tests Undefined 
PASS Tests matchesNothingInDataset 
FAIL Tests Set Test bug: need to pass exception to assert_throws()
PASS Tests Is Null 
PASS Tests Delete 
PASS Tests Native Delete 
PASS Tests For In 
PASS Set null 
Harness: the test ran to completion.

