This is a testharness.js-based test.
FAIL createAnswer() with null remoteDescription should reject with InvalidStateError assert_unreached: Should have rejected: undefined Reached unreachable code
FAIL createAnswer() after setting remote description should succeed promise_test: Unhandled rejection with value: object "OperationError: TEST_ERROR"
FAIL createAnswer() when connection is closed reject with InvalidStateError promise_test: Unhandled rejection with value: object "OperationError: TEST_ERROR"
FAIL createAnswer() when connection is closed in parallel should never resolve assert_unreached: Pending promise should never be resolved. Instead it is rejected with: OperationError: TEST_ERROR Reached unreachable code
Harness: the test ran to completion.

