This is a testharness.js-based test.
FAIL Must throw if it encounters an unknown currencySystem assert_throws: function "() => {
    const invalidAmount = {
      ...validAmount,
      currencySystem: "this will cause the TypeError"
    }
    const invalidDetails = {
      total: {
        label: "",
        amount: invalidAmount,
      },
    };
    const request = new PaymentRequest(validMethods, invalidDetails);
  }" did not throw
Harness: the test ran to completion.

